### PR TITLE
Regenerate CLDF with sources and update metadata

### LINKED ISSUE #1: add sources
```
Spanish&Lexicon: Personal knowledge. Transcription: \cite{Martinez-Celdran2003IllustrationsSpanish} \\ 
Mandarin Chinese&Lexicon: Personal knowledge. Transcription: \cite{Duanmu2007TheChinese} \\ 
Yoruba&\cite{Fakinlede2003English-YorubaDictionary} \\ 
Egyptian Spoken Arabic&Lexicon: \cite{Stevens2004}, p. c. with a speaker. Transcription: \cite{Watson2011TheArabic} \\ 
Javanese&\cite{Sukanda2016ParlonsLexicons, Robson2002} \\ 
Telugu&Lexicon: \cite{Bosse1994ParlonsTelugu, Collooru2017Telugu-English/English-TeluguPhrasebook, Gwynn1991ADictionary}. Transcription: \cite{Krishnamurti2015Telugu} \\ 
Turkish&Lexicon: \cite{Alderson1978}. Transcription: \cite{Zimmer1992Turkish} \\ 
Japanese&Lexicon: Personal knowledge. Transcription: \cite{Labrune2012} \\ 
Vietnamese&Lexicon: Personal knowledge. Transcription: \cite{Kirby2011Vietnamese} \\ 
Thai&Lexicon: Personal knowledge. Transcription: \cite{Iwasaki2005} \\ 
Korean&Personal knowledge (I am a native speaker) \\ 
Dholuo&Lexicon: \cite{BlountLUOGrammar.}, \cite{Malandra1957English-LwooDictionary}, \cite{Gorman1972ADholuo}. Transcription: \cite{Odhiambo2010ParlonsKenya} \\ 
Hungarian&Lexicon: \cite{Orszagh1990}, consultation of an online dictionary. Transcription: \cite{Siptar2000} \\ 
Chuanqiandian Cluster Miao&\cite{XiongYuYou2014Miao, XingGui2004:Dialect, ShiLiYun2016366Miao} \\ 
South Bolivian Quechua&\cite{LaimeAjacopa2007DiccionarioSpanish-Quechua, Herrero1974DiccionarioQuechua, Urioste1955GramaticaLanguage} \\ 
Peripheral Mongolian&\cite{DaoBu1983}\\ 
Kabardian&Lexicon: \cite{Jaimoukha2009ParlonsDialect, Kardanov1955Russko-kabardinsko-cherkesskijDictionary, Apazhev2013Kabardinsko-russkijDictionary}. Transcription: \cite{Jaimoukha2009KabardianPhonetics} \\ 
K'iche'&\cite{GarciaHernandez1980DiccionarioDictionary, Christenson1993} \\ 
Paraguayan Guarani&Lexicon: \cite{Guasch2008DiccionarioIdeological,Britton2005GuaraniDictionary}. Transcription: \cite{Walker1999GuaraniStudy} \\ 
Georgian&Lexicon: \cite{Gvarjalaze2003English-GeorgianLeksikoni, Awde2010}, p. c. with a native speaker. Transcription: \cite{Shosted2006} \\ 
Enga&P. c. with Adam Boyd (Enga Bible Translation Program) \\ 
Eastern Huasteca Nahuatl&P. c. with John Sullivan (Uniwersytet Warszawski and Universidad Autónoma de Zacatecas) \\ 
Central Aymara&\cite{de.LuccaD.1983Aymara-SpanishCastellano-aymara., Carvajal2001IllustratedIngles} \\ 
Meqzuital Otomi&Lexicon: \cite{Hernandez-CruzLuisVictoriaTorquemada2010DiccionarioState, Wallis1956DiccionarioDictionary}. Transcription: \cite{Blight1976TheOtomi} \\ 
Wayuu&Lexicon: \cite{Captain2005DiccionarioSpanish-Wayuu}. Transcription: \cite{SouthAmericanPhonologicalInventoryDatabase2014WayuuSAPHON}\\ 
Basque&\cite{Aulesta1990} \\ 
Ngäbere&\cite{Alphonse1956GuaymiNotes} \\ 
Highland Totonac&\cite{Aschmann1983Castellano-TotonacoDialect} \\ 
Khoekhoe&Lexicon: \cite{Haacke2002}. Transcription: \cite{Brugman2009} \\ 
Galela&Lexicon: P. c. with a native speaker. Transcription: \cite{Shelden1989GalelaStress} \\ 
Mapudungun&Lexicon: \cite{Golluscio2009MapudungunVocabulary}. Transcription: \cite{Sadowsky2013Mapudungun} \\ 
Western Highland Purepecha&\cite{Perez2000VocabularioVocabulary, Chamoreau2003ParlonsMexico}, p. c. with Claudine Chamoreau (CNRS) \\ 
Woods Cree&\cite{Castel2001CastelsElders,Starks1992AspectsSyntax}, p. c. with Arok Wolvengrey (First Nations University of Canada) \\ 
Navajo&\cite{Young1980,Young2014TheEnglish} \\ 
Highland Popoluca&\cite{deJongBoudreault2009ALanguage}, p. c. with Lynda J. de Jong Boudreault \\ 
Ambulas&\cite{Kundama2006}, p. c. with Richard Scaglion (University of Pittsburgh) \\ 
Mískito&\cite{Berckenhagen1906PocketEnglish-Miskito-Spanish, Heath1953DiccionarioDictionary} \\ 
Shuar&Lexicon: \cite{Borman1991ListasLanguages, InstitutoBilingueInterculturalShuar1988ChichamSpanish-Shuar,Paati2012VisionShuar} \\ 
Northern Emberá&\cite{Sara2001} \\ 
Bukiyip&Unpublished field notes of Lise M. Dobrin (University of Virginia) \\ 
Northwestern !Kung&\cite{Konig2008}, p. c. with Bonny Sands (Northern Arizona University) \\ 
Greenlandic&\cite{Oqaasileriffik2017GreenlandicDictionary}, p. c. with Minik Jeremiassen (Language Secretariat of Greenland) \\ 
Burushaski&\cite{Berger1974DasWerchikwar, Tiffou1999ParlonsBurushos}. Note: Yasin dialect. \\ 
Sentani&\cite{Cowan1965GrammarLanguage} \\ 
Terei&\cite{Laycock2003ABougainville} \\ 
Macushi&Lexicon: \cite{Amodio1996LinguaLanguage}. Transcription: \cite{Miriam2010Macushi} \\ 
Ap Ma&P. c. with Jill Riepe, p. c. with Jesse and Karie Pryor (Outreach International of Papua New Guinea) \\ 
Páez &\cite{Slocum1983DiccionarioDictionary, Arias2012,Rojas1998LaGrammar}. Transcription: \cite{Rojas1998LaGrammar} \\ 
Wichí Lhamtés Vejoz&\cite{Nercesian2014WichiInteraction, Vidal2009WichiVocabulary} \\ 
Sandawe&\cite{Ehret2012ATanzania, Kagaya1993ALanguage}. Note: Tones not transcribed in \cite{Kagaya1993ALanguage}  \\ 
Xibe &\cite{Hanxi1989} \\ 
Toba &\cite{Messineo2003LenguaAspects, MessineoVocabularioParaguay, Buckwalter2013VocabularioVocabulary} \\ 
Ticuna &\cite{MontesRodriguez2004MorfosintaxisLanguage} \\ 
Kaingang&\cite{Wiesemann2011DicionarioDictionary} \\ 
Pitjantjatjara&\cite{Goddard1993APitjantjatjara/Yankunytjatjara, Goddard1996}, p. c. with Cliff Goddard (Griffith University) \\ 
Guahibo &\cite{Kondo2014DiccionarioEspanol-Guahibo}, p. c. with Francesc Queixalós (CNRS) \\ 
Shipibo-Conibo&Lexicon: \cite{Loriot1993DiccionarioDictionary, Valenzuela1997}. Transcription: \cite{Valenzuela2001Shipibo} \\ 
Yanomamö&\cite{Lizot2004DiccionarioLanguage} \\ 
Tucano &\cite{Ramirez1997AYepa-masa} \\ 
Warao&Lexicon: \cite{de.Barral1979DiccionarioDictionary, PonceDiccionarioDictionary}. Transcription: \cite{Romero-Figueroa1997AWarao}. Note: Only the morpheme for `hard' retrieved from \cite{PonceDiccionarioDictionary}, an online dictionary. Nasal diacritics are not transcribed in \cite{PonceDiccionarioDictionary}.  \\
Awa-Cuaiquer&\cite{Curnow1997,Henriksen1969MuestraCwaiquer,Henriksen1969Swadesh-RoweKwaiker} \\ 
Mai Brat&\cite{Kambuaya1989AamVocabulary} \\ 
Piaroa&\cite{KrisologoB.1976ManualLanguage} \\ 
Amanab&P. c. with Andy Minch (SIL) \\ 
Choctaw&\cite{Broadwell2006, Byington1915ALanguage} \\ 
Cherokee&\cite{Montgomery-Anderson2008ACherokee, Nation2017DikaneisdiList} \\ 
```
Thanks to @ianjoo for sending the references from bibtex. I have included the bibtex file already. All we will need is: add the sources to the `languages.csv`, so we can use those in order to reference the data properly.

### LINKED ISSUE #7: Paper appeared officially: Citation should be adjusted
https://doi.org/10.1515/lingty-2019-0030

### PR DESCRIPTION
**Pull request by chrzyki**
Closes #7 and #1

### CODE REVIEW

**Comment by chrzyki** [comment]
By the way, there is only a total of 65 languages in `languages.csv`, the paper mentions 66 languages. Is this mentioned somewhere or is there a language missing?

**Comment by ianjoo** [comment]
The LJ list of Bukiyip was not disclosed due to the request from the contributor.

**Comment by chrzyki** [comment]
> The LJ list of Bukiyip was not disclosed due to the request from the contributor.

Ah, thanks for clarifying!

**Comment by LinguList** [comment]
> The LJ list of Bukiyip was not disclosed due to the request from the contributor.

Maybe, adding this to "NOTES.md" would be useful.

**Review by LinguList — COMMENTED** [review]
One thing: could we modify contributors.md, to account for our new style?

Ian should be author, for Zenodo, @chrzyki and myself should be listed as "OTHER", and in the table, it shoudl say "cldf conversion". That means, @ianjoo, Zenodo will list you as only author, but @chrzyki and myself will be listed on zenodo as the persons who helped with cldf conversion, which is also important in case of errors in our conversion process, so we know who was responsible, etc.

**Comment by chrzyki** [comment]
@ianjoo do you have a preferred text that should be included in the `NOTES.md` and is displayed for the dataset? I'll also update the contributors as per Mattis' suggestions.

**Pull request merged**
