### PR TITLE
Strip forms of spaces before processing, fixes  #9

### LINKED ISSUE #9: Final space in token
There is a final space in the token below:

https://github.com/lexibank/joophonosemantic/blob/b5bad5aede5715848c6299720071122b73fce7f9/cldf/forms.csv#L96

Which results in a None in the Segments when reading with `get_dataset(...).cldf_reader()`: 

~~~
OrderedDict([('ID', 'WesternHighlandPurepecha-9_2sgpronoun-1'), ('Local_ID', None), ('Language_ID', 'WesternHighlandPurepecha'), 
('Parameter_ID', '9_2sgpronoun'), ('Value', 'tʰ.u '), ('Form', 'tʰ.u '), ('Segments', ['tʰ', 'u', None]), 
('Comment', None), ('Source', ['Perez2000VocabularioVocabulary', 'Chamoreau2003ParlonsMexico']), 
('Cognacy', None), ('Loan', None), ('Graphemes', None), ('Profile', None), ('dataset', 'joophonosemantic')])
~~~

### PR DESCRIPTION
**Pull request by XachaB**
This is a fix to issue #9, where some forms retained a final space.

### CODE REVIEW

**Review by chrzyki — APPROVED** [review]
Very nice, thank you! Only think I'd ask/change is to re-run lexibank.makecldf with pylexibank==2.7.2 please. Thanks. :)

**Comment by XachaB** [comment]
I merged master in because in the mean time Tiago did the orthography profile. Adding the `strip()` was still necessary because otherwise we now get final "+" in forms. 

I also cleaned up a bit code which is not useful anymore after making the profile.

The test now throws a warning:
```

================================================================================================================================ warnings summary ================================================================================================================================
../lexibank/lib/python3.6/site-packages/_pytest/config/__init__.py:1230
  /home/beniamine/Data/Lexibank/lexibank/lib/python3.6/site-packages/_pytest/config/__init__.py:1230: PytestConfigWarning: Unknown config option: mock_use_standalone_module
  
    self._warn_or_fail_if_strict("Unknown config option: {}\n".format(key))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================================================================== 4 passed, 1 warning in 2.58s ==========================================================================================================================

```

Any idea how to solve it ?

**Review by chrzyki — APPROVED** [review]
Looks fine, thanks! Just make sure to pull in master (i.e. Tiago's profile).

Re mock_use_standalone_module: Looks like you don't have `pytest-mock` installed? (`pip install pytest-mock`)

**Comment by XachaB** [comment]
commit a3e108a did merge master into this branch, so it has the orthography profile.
Now installed pytest-mock and everything runs fine.

As I was re-generating everything, I saw the following error:

~~~
ERROR   Mapping [̃ĩ] (U+0303 U+0129) -> [̃ĩ] (U+0303 U+0069 U+0303) includes an unknown sound.
~~~

This is due to two tildes on the i (one before, one after), and I have fixed it in the profile and re-generated. I think in the end it had no impact on the forms, as the table was not changed. It is still cleaner to not have the faulty mapping.

**Comment by chrzyki** [comment]
Sounds reasonable, thanks for taking care of this!

**Pull request merged**
